default:
	python3 execution_perf.py default

cupy:
	python3 execution_perf.py cupy

pytorch:
	python3 execution_perf.py pytorch

res:
	python3 execution_perf res

dt:
	python3 execution_perf dt

nu:
	python3 execution_perf nu

requirements:
	pip install -r requirements.txt
